<table>
	<tr>
		<td>
			<label for="export_type_default">
				<input type="radio" name="export_type" id="export_type_default" checked="checked" value="excel"> 
				Export the selected rows
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="export_type_last_result">
				<input type="radio" name="export_type" id="export_type_last_result" value="last_result"> 
				Last Test Result for the selected releases
			</label> 
		</td> 
	</tr> 
</table> 
