Please select the Add Cases type:
<table>
	<tr>
		<td>
			<label for="add_from_codec_strem">
				<input type="radio" name="case_add_type" id="add_from_codec_strem" checked="checked" value="stream_list"> 
				Add Cases From Stream List And TrickModes To Codec Cycle
			</label> 
		</td> 
	</tr>
	<tr>
		<td>
			<label for="add_from_cycle">
				<input type="radio" name="case_add_type" id="add_from_cycle" value="cycle_list"> 
				Add Cases From Other Cycle To Codec Cycle
			</label> 
		</td> 
	</tr>
</table> 
