<!--
<div id='ver_diff'>
<?php
//	echo $this->partial('/xt/zzvw_testcase_ver/testcase_ver_diff.phtml', array('vers'=>$this->vers));
?>
</div>
<div id='select-reviewers'>
	<p>Please select reviewers:</p>
	<div id='reviewers'>
			<?php
//			print_r($this->reviewers);
/*
			foreach($this->reviewers as $k=>$reviewer){
				print_r("<label><input type='checkbox' value='$k' name='reviewers'>{$reviewer}</label>");
			}
*/			
			?>
			
	</div>
</div>

<div id='op_button'>
	<button type='button' id='btn_ask2review'>Ask to Review</button>
</div>
-->