<?php
//$this->form->setAction($this->url());
echo $this->form;
?>

<script type='text/javascript'>
    function ajax_changePwd(event, btn){
		var tool = new kf_tool();
        var newPwd = $('#password').val();
        var confirm = $('#password_confirm').val();
        var length = newPwd.length;
        // check if they are the same
        if (newPwd != confirm)
            tool.noticeDialog("The password you typed do not match. Please check it", "Password not match");
        else if (length < 6)
            tool.noticeDialog("The password you typed is too short (>= 6). Please check it", "Password is too short");
        else if (length > 20)
            tool.noticeDialog("The password you typed is too long (<=20). Please check it", "Password is too long");
        else{
            $.ajax({
                type:'POST',
                url:'/useradmin/changepassword',
                data:'password=' + newPwd + '&password_confirm=' + confirm,
                success:function(msg){
                    var tabId = tool.getTabId(btn);
tool.debug(tabId);
tool.debug(msg);
                    if (msg == 'true'){
                        tool.noticeDialog("Success to changed the password");
                        $('#mainContent').tabs('remove', tabId);
                    }
                    else{
                        $('#' + tabId).html(msg);
                    }
    //                alert(msg);    
                } 
            });
        }
    }
</script>