<div>
<span style="color:gray">From:</span><span id="from" style="color:green"><?php echo $this->from; ?></span><BR />
<span style="color:gray">Subject:</span><span id="subject" style="color:green"><?php echo $this->subject; ?></span><BR />
<span style="color:gray">Message:</span><div id="message" style="color:red" disabled="disabled" rows=8 cols=80><?php echo $this->message; ?></div><BR />
</div>