<table>
	<tr>
		<td>
			<label for="script_type_auto">
				<input type="radio" name="script_type" id="script_type_auto" value="1"> 
				Auto Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_auto_manual">
				<input type="radio" name="script_type" id="script_type_auto_manual" value="2"> 
				Auto/Manual Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_skywalker">
				<input type="radio" name="script_type" id="script_type_skywalker" value="3"> 
				Skywalker Script
			</label> 
		</td> 
	</tr> 
</table> 
