<table width='80%'>
	<tr>
		<td>
			<label for="export_type_last_result">
				<input type="radio" name="export_type" id="export_type_last_result" value="last_result"> 
				Cycle Report
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_auto">
				<input type="radio" name="export_type" id="script_type_auto" value="auto_script"> 
				Auto Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_auto_manual">
				<input type="radio" name="export_type" id="script_type_auto_manual" value="auto_manual_script"> 
				Auto/Manual Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_skywalker">
				<input type="radio" name="export_type" id="script_type_skywalker" value="skywalker_script"> 
				Skywalker Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_sorted_skywalker">
				<input type="radio" name="export_type" id="script_type_sorted_skywalker" value="sorted_skywalker_script"> 
				Sorted Skywalker Script: testcaseid_H*L* commandline
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="script_type_bsp_config">
				<input type="radio" name="export_type" id="script_type_bsp_config" value="bsp_config"> 
				BSP Config Script
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="export_type_testcase_release">
				<input type="radio" name="export_type" id="export_type_testcase_release" value="rel"> 
				Testcases Release(HTML)
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="export_type_testcase_excel_release">
				<input type="radio" name="export_type" id="export_type_testcase_excel_release" value="excel_rel"> 
				Testcases Release(Excel)
			</label> 
		</td> 
	</tr> 
</table> 
