<form id='import_form' enctype="multipart/form-data" method='post' action='/jqgrid/jqgrid/oper/import/db/<?php echo $this->db;?>/table/<?php echo $this->table;?>' target='hidden_frame'>
	<?php
		$ces = array(
			array('name'=>'owner_id', 'label'=>'Owner', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->owner), 'defval'=>$this->defval_owner),
			array('name'=>'config_file', 'label'=>'Config Type', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->config_file)),
			array('name'=>'uploaded_file', 'label'=>'File', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'file')
		);
		$tool = toolFactory::get('kf');
		$tool->cf($ces, true, 'new');
	?>
</form>
<iframe name='hidden_frame' id='hidden_frame' width="100%"></iframe>

