<?php
    if ($this->from == 'wz'){ // 入口是物资，则物资名称是固定的，而供应商是可选的
?>
        <label for='cg_wz'>物资:<input type='text' name='cg[wz]' id='cg_wz' value="<?php echo $this->wz; ?>" /></label>
        <label for='cg_hb_id'>供应商:<select id='cg_bh_id' name='cg[hb_id]'> 
        <?php
            foreach($this->hb as $hb){
                echo '<option value="'.$hb['id'].'">'.$hb['name'].'</option>'; 
            }
        ?>
        </select></label><BR />
<?php    
    }
    else if ($this->from = 'hb'){ // 入口是合作伙伴，则供应商是固定的，而物资名称是可选的
?>
        <label for='cg_hb_id'>供应商:<input type='text' name='cg[hb_id]' id='cg_bh_id' value="<?php echo $this->hb; ?>" /></label>
        <label for='cg_wz'>物资:<select id='cg_wz' name='cg[wz]'> 
        <?php
            foreach($this->ht as $ht){
                echo '<option value="'.$ht['wz_id'].'">'.$ht['wz'].'</option>'; 
            }
        ?>
        </select></label><BR />
<?php    
    }
?>
    <label for='cg_price'>单价：<input type='text' id='cg_price' name='cg[price]' /></label>
    <label for='cg_amount'>数量：<input type='text' id='cg_amount' name='cg[amount]' /></label><?php echo $this->ht[0]['count_unit']; ?><BR />
    
    <?php
    echo $this->partial('zf.phtml', array('type'=>'wz', 'title'=>'采购', 'zjzh'=>$this->zjzh));
    ?>
    
    <label for ='ruku'>现在入库？<input type='checkbox' id='ruku' checked='false'></label>
    <div id='div_ruku'>
        <?php 
            echo $this->partial('wz_rk.phtml', array('yunshu'=>$this->yunshu, 'zhuangxie'=>$this->zhuangxie, 'zjzh'=>$this->zjzh));
        ?>
    </div>         
