<?php
//<!-- 员工技能 -->
    require_once('kf_tool.php');
    $tool = new kf_tool();
    $es = array(
        array('type'=>'div', 'id'=>'div_yg'),
            array('type'=>'div', 'id'=>'div_is_yg'),
                array('type'=>'checkbox', 'id'=>'is_yg', 'name'=>'is_yg', 'label'=>'是否员工')，
            array('type'=>'/div'),
            // 员工信息
            array('type'=>'select', 'id'=>'yg_gender', 'name'=>'gender', 'label'=>'性别', 'option'=>array(array('id'=>1, 'name'=>'男'), array('id'=>2, 'name'=>'女'))),
            array('type'=>'select', 'id'=>'yg_salary_class', 'name'=>'salary_class_id', 'label'=>'工资类型', 'option'=>$this->salary_class),
            array('type'=>'text', 'id'=>'yg_base_salary', 'name'=>'base_salary', 'label'=>'基本工资'),
            array('type'=>'text', 'id'=>'yg_ticheng_ratio', 'name'=>'ticheng_radio', 'label'=>'提成比例'),
            //员工技能信息
            array('type'=>'fieldset', 'id'=>'yg_skill', 'legend'=>'员工技能'),
                array('type'=>'div', 'id'=>'yg_skill_inner'),
                    array('type'=>'div', 'id'=>'yg_skill_temp'),
                        array('type'=>'select', 'id'=>'yg_gx', 'name'=>'gx[]', 'label'=>'工序', 'option'=>$this->gx),
                        array('type'=>'select', 'id'=>'yg_grade', 'name'=>'grade[]', 'label'=>'熟练程度', 'option'=>$this->grade),
                    array('type'=>'/div'),
                array('type'=>'/div'),   
                array('type'=>'button', 'id'=>'yg_add_skill', 'value'=>'+', 'onclick'=>"yg_addSkill('yg_skill_inner', 'yg_skill_temp')"),                     
            array('type'=>'/fieldset'),
        array('type'=>'/div')
    );
    $tool->createElements($es);
?>
