<form id='detail_log_import_form' enctype="multipart/form-data" method='post' action='/jqgrid/jqgrid/oper/log_import/db/<?php echo $this->db;?>/table/<?php echo $this->table;?>' target='detail_log_hidden_frame'>
<?php
	require_once('toolfactory.php');
	$tool = toolFactory::get('kf');
	$params = isset($this->params) ? $this->params : array();
	$ms = count($this->cols);
	if ($ms < 8)
		$cols = 1;
	else
		$cols = 1;
	print_r("<fieldset><legend>{$this->legend}</legend>");
		$tool->cf($this->cols, true, null, $cols, false, $params, true);
	print_r("</fieldset>");
	print_r("<div id=div_result_bug_submit_".$this->id."></div>");
	?>
</form>
<?php
	if(!empty($this->btn)){
		//print_r('<iframe name="hidden_frame" id="hidden_frame" width="100%"></iframe>');
		print_r("<button id='save' onclick='' title='Save' type='button' style='width:100px;height:30px;position:relative;float:right' >Save</button>");
		print_r("<button id='cancel' onclick='' title='Cancel' type='button' style='width:100px;height:30px;position:relative;float:right'>Cancel</button>");	
	}
?>
