<div id='div_view_edit'>
	<fieldset>
	<?php
		echo $this->partial($this->node['view_file'], $this->node);
	?>
	</fieldset>
</div>
<div id="div_button_edit">
<?php
	echo $this->partial('button.phtml', $this);
?>
</div>
<?php
if($this->id < 0) {//> 0){
print_r($this->table);
?>	
<BR>
<div style="width:100%">
	<fieldset><legend>Test Steps Result</legend>
		<table id='div_information_<?php $this->db.'_'.$this->table?>_xt_zzvw_cycle_detail_step_list'></table>
		<div id='div_information_<?php $this->db.'_'.$this->table?>_xt_zzvw_cycle_detail_step_list'></div>
	</fieldset>
</div>
<?php
}
?>