<?php
	$columnMap = array(
		'default'=>array(
			'start_row'=>2,
			'columns'=>array(
				'testcase_module'=>'B',
				'code'=>'C',
				'summary'=>'D',
				'precondition'=>'E',
				'steps'=>'F',
				'expected_result'=>'G',
				'testcase_priority'=>'H',
				'testcase_testpoint'=>'I',
				'testcase_category'=>'J',
				'MQX'=>'N',
				'Linux'=>'O',
				'testcase_source'=>'P',
				'auto_level'=>'Q',
				'command'=>'S',
			)
		)
	);
?>