<table>
	<tr>
		<td>
			<label for="export_type_default">
				<input type="radio" name="export_type" id="export_type_default" checked="checked" value="excel"> 
				Export the selected rows
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="export_type_summary_report">
				<input type="radio" name="export_type" id="export_type_summary_report" value="summary_report"> 
				Summary Report
			</label>
			<div id='div_for_summary_report_options' style='display:none;position:relative;left:40px'>
				<label for='period_id'>Period:</label><br />
				<select id='period_id'>
					<?php
						foreach($this->periods as $id=>$name){
							print_r("<option value='$id'>$name</option>");
						}
					?>
				</select><br/><br/>
				<label for='levels'>Note Level</label><br/>
				<select id='levels'>
					<option value='son-level' selected='selected'>Son-level Notes Only</option>
					<option value='myself-level'>Myself Notes Only</option>
					<option value='sub-levels'>All Sub-level Notes</option>
				</select>
			</div>
		</td> 
	</tr> 
</table> 
