<fieldset><legend>Please select reviewer groups:</legend>
	<div id='reviewer_groups'>
		<?php
		// groups
		foreach($this->reviewer_groups as $k=>$group){
			print_r("<label><input type='checkbox' value='$k' name='reviewer_groups'>{$group}</label> ");
		}
		?>
	</div>
</fieldset>
<fieldset><legend>Please select reviewers:</legend>
	<div id='reviewers'>
		<?php
		// person
		foreach($this->reviewers as $k=>$reviewer){
			print_r("<label><input type='checkbox' value='$k' name='reviewers'>{$reviewer}</label> ");
		}
		?>
	</div>
</fieldset>
<p>Please Select a main reviewer:<select id='main_reviewer'>
<?php
	foreach($this->reviewers as $k=>$reviewer){
		print_r("<option value='$k'>$reviewer</option> ");
	}
?>	
</select></p>
<div style="width:100%">
	<label for="deadline">Please input the deadline:</label><input type='text' id='deadline' value='<?php echo date('Y-m-d', strtotime('+1 week'));?>'><BR><BR>
	<label for="ask2review_comment">Please input the message:</label><textarea id='ask2review_comment' rows='5' cols='80'><?php echo $this->comment; ?></textarea>
</div>

