<!--
Node--Ver结构的统一编辑样式
-->
<div id='div_view_edit'>
	<input type='hidden' id='node_id' value='<?php echo isset($this->node['value']['id']) ? $this->node['value']['id'] : 0; ?>' />
	<div id='node_info'>
	<?php
		$node_view_file = $this->node['view_file'];
		// if (!empty($this->node['view_file_dir']))
			// $node_view_file = $this->node['view_file_dir'].'/'.$this->node['view_file'];
//print_r("file = $node_view_file and dir = {$this->node['view_file_dir']}");
//		echo $this->partial($this->node['view_file'], $this->node);
		echo $this->partial($node_view_file, $this->node);
	?>
	</div>
	<div id='detail_info'>
		<?php
		if (!empty($this->detail)){
			$detail_view_file = $this->detail['view_file'];
			// if (!empty($this->detail['view_file_dir']))
				// $detail_view_file = $this->detail['view_file_dir'].'/'.$this->detail['view_file'];
//			echo $this->partial($this->detail['view_file'], $this->detail);
			echo $this->partial($detail_view_file, $this->detail);
		}
		?>
	</div>
</div>

<div id="div_button_edit" style="width:100%">
	<?php
	echo $this->partial('button.phtml', $this);
	?>
</div>

<fieldset id='fieldset_reference' style='display:none'>
	<legend align="center"><b>Reference From Other Notes</b></legend>
	<div id="div_reference">
	</div>
</fieldset>