<p>Please select projects to <span style="color:red">UNLINK:</span></p>
<?php
	print_r("<table><tbody>");
	$i = 0;
	print_r("<tr>");
	foreach($this->projects as $project){
//print_r($project);		
		$checked = 'checked="checked"';
		$color = 'style="color:red"';
		if (empty($project['linked'])){
			$checked = '';    
			$color = '';
		}
		print_r('<td '.$color.'><label><input type="checkbox" name="projects[]" '.$checked.' value="'.$project['id'].'"/>'.$project['name'].'</label></td>');
		$i ++;
		if ($i % 4 == 0){
			print_r("</tr>");
		}
	}
	if ($i % 4)
		print_r("</tr>"); 
	print_r("</tbody></table>");
?>
