<fieldset><legend><label><input type=checkbox id='has_yunshu'>运输</label></legend>
	<div id='div_yunshu' style='display:none'>
	<?php
		$ces = array(
			array('label'=>'承运人', 'name'=>'yunshu[hb_id]', 'id'=>'yunshu_hb_id', 'type'=>'select', 'DATA_TYPE'=>'int', 'editable'=>true, 'editoptions'=>array('value'=>$this->cyr)),
			array('label'=>'运输日期', 'name'=>'yunshu[happen_date]', 'id'=>'yunshu_happen_date', 'type'=>'date', 'DATA_TYPE'=>'date', 'editable'=>true, 'defval'=>date('Y-m-d')),
			array('label'=>'数量', 'name'=>'yunshu[amount]', 'id'=>'yunshu_amount', 'type'=>'text', 'post'=>'吨', 'DATA_TYPE'=>'float', 'editable'=>true),
			array('label'=>'运输单价', 'name'=>'yunshu[price]', 'id'=>'yunshu_price', 'type'=>'text', 'post'=>'元/吨', 'DATA_TYPE'=>'float', 'editable'=>true),
			array('label'=>'总运费', 'name'=>'yunshu[total]', 'id'=>'yunshu_total', 'type'=>'text', 'post'=>'元', 'DATA_TYPE'=>'float', 'editable'=>false),
		);
		$tool = toolFactory::get('kf');
		$tool->cf($ces, true, null, 3, false, array(), true);

		echo $this->partial('zf.phtml', array('type'=>'yunshu_zf', 'title'=>'运输费', 'zjzh'=>$this->zjzh, 'jbr'=>$this->jbr));
	?>
	</div>
</fieldset>
